---
- hosts: ansible

  tasks:
    - name: clone repository
      git:
        repo: https://github.com/AveryCorniell/BellyButtonDiversity.git
        dest: /opt/docker/bellybutton-app
        clone: yes
        update: yes

    - name: create docker image
      command: docker build -t bellybutton-app:latest /opt/docker/bellybutton-app
      args:
        chdir: /opt/docker/
    
    - name: create tag to push image to Docker Hub
      command: docker tag bellybutton-app:latest averycorniell/bellybutton-app:latest

    - name: push docker image
      command: docker push averycorniell/bellybutton-app:latest

